language: node_js
before_install:
- cd functions
install:
- npm install
before_deploy:
- cd ..
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: WzLl/14Lr5DBg/WFA2awHpnS45BZOM0DjYESsWvoxpzSnTk0b66pdcRUf/pBid8KsXYny8+clCx+Qn9quCHRl7iGXSH5SvI0UtiYJlkBXLf6mUK7Haid1VLJMIoFuTsEmqgGTf6o7xGLasV54CLiyeyvyVbSrTMVhziOrn1w4ldctWvr5tVknkimEPdDrEQEOSxqQdpGWTMyOH83dxwyimW+N6qO3MpEqmNmrkcTLQIxtvrgic7vW+24up7P2MvGwhqSBlC7p2FMXZG7Jah8Q5oE0gcW9hji/Zg4chwoUATS7zNq/rwrWoVFAqLsM+AOe2K9DmWRdCSl2O1cn1w9jZUEalCAVeeBa05k52bheoD7szSPhDVsOOlv91VPx+FCQQdw+ITSlCtGr7bub5aw5eN3fgZQmX3EOcHV9SgesyPAwU6b7twj5fjzJjiTFxHcsbg6XaaVy2DveBMd1dyQf66Av3EKoq5upjlmrADYVFQtKDH2Fi/T/uGFoGgnez7TaClR4XZwL3K2VrevBX/iGmOBnFyZX9G3n9c8sEH57BsKZDi5KvG4rE/WrhHIGtMGOsxI+lE75RvyogQpgPT/szKJszhARpHs04LLIYtXvaHM6oTC0o9mkKX8NMIExZtxs6xLALGdc1OgIes4ikjpSEoPQH/vixY4iJ4QX+ANR4o=
